name: Deploy to InfinityFree

on:
  push:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Install Composer deps
        run: composer install --no-dev --optimize-autoloader --no-interaction --no-scripts

      - name: Deploy Laravel app folder
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftp
          local-dir: ./
          server-dir: /htdocs/laravel_app/
          log-level: verbose
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/**
            public/**
            .env
            storage/logs/**
            storage/framework/cache/**
            storage/framework/sessions/**
            storage/framework/views/**

      - name: Deploy public folder to web root
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftp
          local-dir: ./public/
          server-dir: /htdocs/
          log-level: verbose
          exclude: |
            **/.git*
            **/.git*/**
